<?php
// $Id: no_password.module,v 1.0 2011/06/06 9:30:00 lkuempel Exp $

/**
 * @file
 *
 * Hide password fields, hard code password and disable "request new password". User does not use a password.
 */

/*******************************************************************************
 * Hook Functions (Drupal)
 ******************************************************************************/

/**
 * Implementation of hook_form_alter().
 */
function no_password_form_alter(&$form, &$form_state, $form_id) {
	global $user;
	if (!user_access('administer') && ($_GET['q'] != 'admin/login')) {
		
        //This was left over from D6.  This is being done by another module now...
        //if (($form_id == 'user_register') || ($form_id == 'user_login') || ($form_id == 'user_profile_form')) {
		//	if (isset($form['account']['pass'])) {
		//		$form['account']['pass'] = _no_password_hide($form['account']['pass']);
		//	} else if (isset($form['pass'])) {
		//		$form['pass'] = _no_password_hide($form['pass']);
		//	}
		//}

        //Remove password field from user login block
        if ($form_id == 'user_login_block') {
            //watchdog('gabe2', print_r($form));
            
            //hide PW field, and change its value to 'no_password'
            if (isset($form['pass'])) {
                $form['pass'] = _no_password_hide($form['pass']);
            }

            //Hide links to create new account, and forgot password
            if (isset($form['links'])) {
                $form['links'] = "";
            }

            //re-arrange form so that custom text is at top of form.
            $customText = t("Already registered for this event? Enter your email below and hit LOG IN to enter.");
            $tmpArray = array('some_text' => array('#markup' => '<p>' . $customText . '</p>')) + $form;
            $form = $tmpArray;

            //$form['some_text'] = array(
            //    '#markup' => '<p>Some text</p>'
            //);

        }
	}

    //watchdog('gabe', $form_id);
}
/**
 * Implementation of hook_menu().
 */
function no_password_menu() {
	// Make a spot for admins to login since we might turn off the user/ page
	$items['admin/login'] = array(
		'title' => 'Admin login',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('user_login'),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}

/**
 * Implementation of hook_menu_alter().
 */
function no_password_menu_alter(&$items) {
	// Disable the password request form?
	$items['user/password']['access callback'] = 'user_access';
	$items['user/password']['access arguments'] = array('administer');
}
function _no_password_hide($_field) {
	$_field['#type'] = 'hidden';
	$_field['#value'] = 'no_password';
	$_field['#required'] = 0;
	return $_field;
}

function _no_password_array_unshift_assoc(&$arr, $key, $val) { 
    $arr = array_reverse($arr, true); 
    $arr[$key] = $val; 
    return array_reverse($arr, true); 
} 